apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd-identity
  namespace: default
spec:
  interval: 1h
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/linkerd-identity/production
