---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: application
  namespace: default
spec:
  type: oci
  interval: 5m0s
  url: oci://ghcr.io/microservices-live-projects/manning-live-project-series-kubernetes/charts
  secretRef:
    name: ghcr.io