apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eventuate-cdc
  namespace: default
spec:
  dependsOn:
    - name: customer-service
    - name: order-service
  chart:
    spec:
      chart: eventuate-cdc
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: eventuate
      version: "v0.4.0"
  interval: 15s
  values:
    cdc:
      envFroms: []
      zookeeper: kafka-zookeeper
      kafka: kafka
      databaseServers:
        - customer-service-postgres:
          readerType: postgres-wal
          host: customer-service-postgres
          credentials:
            username:
              valueFrom:
                secretKeyRef:
                  name: customer-service-postgres-database-credentials
                  key: username
            password:
              valueFrom:
                secretKeyRef:
                  name: customer-service-postgres-database-credentials
                  key: password
          databases: 
            - customer_service
        - order-service-postgres:
          readerType: postgres-wal
          host: order-service-postgres
          credentials:
            username:
              valueFrom:
                secretKeyRef:
                  name: order-service-postgres-database-credentials
                  key: username
            password:
              valueFrom:
                secretKeyRef:
                  name: order-service-postgres-database-credentials
                  key: password
          databases: 
            - order_service
