apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: order-service
  namespace: default
spec:
  chart:
    spec:
      version: "0.1.0-BUILD.20231104051348"
  values:
    service:
      enabled: false
    canary:
      enabled: true
