apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api-gateway-service
  namespace: default
spec:
  chart:
    spec:
      version: "0.1.0-BUILD.20231104052113"
  values:
    replicaCount: 1
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/service-upstream: "true"
    canary:
      enabled: true
