apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: github
  namespace: default
spec:
  type: githubdispatch
  address: https://github.com/microservices-live-projects/manning-live-project-series-kubernetes
  secretRef:
    name: github-token
