---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: default-update-automation
  # It only looks for updates in its namespace
  namespace: default
spec:
  interval: 15s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    # specifying checkout/commit branches here prevents testing on a test-branch
    commit:
      author:
        email: chris+fluxcdbot@chrisrichardson.net
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  update:
    path: ./flux/apps
    strategy: Setters