apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: customer-service
  namespace: default
spec:
  chart:
    spec:
      version: "0.1.0-BUILD.20240815194414" # {"$imagepolicy": "default:customer-service-image-policy:tag"}
  values:
    imageUpdateAutomation:
      enabled: true
      image: ghcr.io/microservices-live-projects/manning-live-project-series-kubernetes/charts/customer-service
      policy:
        semver:
          range: ">0.1.0-BUILD <0.2.0-BUILD"
    helmAlert:
      enabled: true
